// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package gs_protocol is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	ReqLogin
	ResLogin
	ReqCreate
	ResCreate
	ReqJoin
	ResJoin
	ReqAction1
	ResAction1
	ReqQuit
	ResQuit
	ReqRoomList
	ResRoomList
	NotifyJoinMsg
	NotifyAction1Msg
	NotifyQuitMsg
	ErrorMsg
*/
package gs_protocol

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Type int32

const (
	Type_Undefined      Type = 0
	Type_Login          Type = 1
	Type_Create         Type = 2
	Type_Join           Type = 3
	Type_DefinedAction1 Type = 4
	Type_Quit           Type = 5
	Type_RoomList       Type = 6
	Type_NotifyJoin     Type = 100
	Type_NotifyAction1  Type = 101
	Type_NotifyQuit     Type = 102
	Type_Error          Type = 1000
)

var Type_name = map[int32]string{
	0:    "Undefined",
	1:    "Login",
	2:    "Create",
	3:    "Join",
	4:    "DefinedAction1",
	5:    "Quit",
	6:    "RoomList",
	100:  "NotifyJoin",
	101:  "NotifyAction1",
	102:  "NotifyQuit",
	1000: "Error",
}
var Type_value = map[string]int32{
	"Undefined":      0,
	"Login":          1,
	"Create":         2,
	"Join":           3,
	"DefinedAction1": 4,
	"Quit":           5,
	"RoomList":       6,
	"NotifyJoin":     100,
	"NotifyAction1":  101,
	"NotifyQuit":     102,
	"Error":          1000,
}

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}
func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}
func (x *Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Type_value, data, "Type")
	if err != nil {
		return err
	}
	*x = Type(value)
	return nil
}

type ErrorType int32

const (
	ErrorType_Unknown ErrorType = 1
)

var ErrorType_name = map[int32]string{
	1: "Unknown",
}
var ErrorType_value = map[string]int32{
	"Unknown": 1,
}

func (x ErrorType) Enum() *ErrorType {
	p := new(ErrorType)
	*p = x
	return p
}
func (x ErrorType) String() string {
	return proto.EnumName(ErrorType_name, int32(x))
}
func (x *ErrorType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorType_value, data, "ErrorType")
	if err != nil {
		return err
	}
	*x = ErrorType(value)
	return nil
}

type ReqLogin struct {
	UserID           *int64 `protobuf:"varint,1,req,name=userID" json:"userID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReqLogin) Reset()         { *m = ReqLogin{} }
func (m *ReqLogin) String() string { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()    {}

func (m *ReqLogin) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

type ResLogin struct {
	UserID           *int64 `protobuf:"varint,1,req,name=userID" json:"userID,omitempty"`
	Result           *int32 `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ResLogin) Reset()         { *m = ResLogin{} }
func (m *ResLogin) String() string { return proto.CompactTextString(m) }
func (*ResLogin) ProtoMessage()    {}

func (m *ResLogin) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *ResLogin) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type ReqCreate struct {
	UserID           *int64 `protobuf:"varint,1,req,name=userID" json:"userID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReqCreate) Reset()         { *m = ReqCreate{} }
func (m *ReqCreate) String() string { return proto.CompactTextString(m) }
func (*ReqCreate) ProtoMessage()    {}

func (m *ReqCreate) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

type ResCreate struct {
	UserID           *int64 `protobuf:"varint,1,req,name=userID" json:"userID,omitempty"`
	RoomID           *int64 `protobuf:"varint,2,req,name=roomID" json:"roomID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ResCreate) Reset()         { *m = ResCreate{} }
func (m *ResCreate) String() string { return proto.CompactTextString(m) }
func (*ResCreate) ProtoMessage()    {}

func (m *ResCreate) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *ResCreate) GetRoomID() int64 {
	if m != nil && m.RoomID != nil {
		return *m.RoomID
	}
	return 0
}

type ReqJoin struct {
	UserID           *int64 `protobuf:"varint,1,req,name=userID" json:"userID,omitempty"`
	RoomID           *int64 `protobuf:"varint,2,req,name=roomID" json:"roomID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReqJoin) Reset()         { *m = ReqJoin{} }
func (m *ReqJoin) String() string { return proto.CompactTextString(m) }
func (*ReqJoin) ProtoMessage()    {}

func (m *ReqJoin) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *ReqJoin) GetRoomID() int64 {
	if m != nil && m.RoomID != nil {
		return *m.RoomID
	}
	return 0
}

type ResJoin struct {
	UserID           *int64  `protobuf:"varint,1,req,name=userID" json:"userID,omitempty"`
	RoomID           *int64  `protobuf:"varint,2,req,name=roomID" json:"roomID,omitempty"`
	Members          []int64 `protobuf:"varint,3,rep,name=members" json:"members,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ResJoin) Reset()         { *m = ResJoin{} }
func (m *ResJoin) String() string { return proto.CompactTextString(m) }
func (*ResJoin) ProtoMessage()    {}

func (m *ResJoin) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *ResJoin) GetRoomID() int64 {
	if m != nil && m.RoomID != nil {
		return *m.RoomID
	}
	return 0
}

func (m *ResJoin) GetMembers() []int64 {
	if m != nil {
		return m.Members
	}
	return nil
}

type ReqAction1 struct {
	UserID           *int64 `protobuf:"varint,1,req,name=userID" json:"userID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReqAction1) Reset()         { *m = ReqAction1{} }
func (m *ReqAction1) String() string { return proto.CompactTextString(m) }
func (*ReqAction1) ProtoMessage()    {}

func (m *ReqAction1) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

type ResAction1 struct {
	UserID           *int64 `protobuf:"varint,1,req,name=userID" json:"userID,omitempty"`
	Result           *int32 `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ResAction1) Reset()         { *m = ResAction1{} }
func (m *ResAction1) String() string { return proto.CompactTextString(m) }
func (*ResAction1) ProtoMessage()    {}

func (m *ResAction1) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *ResAction1) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type ReqQuit struct {
	UserID           *int64 `protobuf:"varint,1,req,name=userID" json:"userID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReqQuit) Reset()         { *m = ReqQuit{} }
func (m *ReqQuit) String() string { return proto.CompactTextString(m) }
func (*ReqQuit) ProtoMessage()    {}

func (m *ReqQuit) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

type ResQuit struct {
	IsSuccess        *int32 `protobuf:"varint,1,req,name=isSuccess" json:"isSuccess,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ResQuit) Reset()         { *m = ResQuit{} }
func (m *ResQuit) String() string { return proto.CompactTextString(m) }
func (*ResQuit) ProtoMessage()    {}

func (m *ResQuit) GetIsSuccess() int32 {
	if m != nil && m.IsSuccess != nil {
		return *m.IsSuccess
	}
	return 0
}

type ReqRoomList struct {
	UserID           *int64 `protobuf:"varint,1,req,name=userID" json:"userID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReqRoomList) Reset()         { *m = ReqRoomList{} }
func (m *ReqRoomList) String() string { return proto.CompactTextString(m) }
func (*ReqRoomList) ProtoMessage()    {}

func (m *ReqRoomList) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

type ResRoomList struct {
	RoomIDs          []int64 `protobuf:"varint,1,rep,name=roomIDs" json:"roomIDs,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ResRoomList) Reset()         { *m = ResRoomList{} }
func (m *ResRoomList) String() string { return proto.CompactTextString(m) }
func (*ResRoomList) ProtoMessage()    {}

func (m *ResRoomList) GetRoomIDs() []int64 {
	if m != nil {
		return m.RoomIDs
	}
	return nil
}

// notify message type (for client)
type NotifyJoinMsg struct {
	UserID           *int64 `protobuf:"varint,1,req,name=userID" json:"userID,omitempty"`
	RoomID           *int64 `protobuf:"varint,2,req,name=roomID" json:"roomID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifyJoinMsg) Reset()         { *m = NotifyJoinMsg{} }
func (m *NotifyJoinMsg) String() string { return proto.CompactTextString(m) }
func (*NotifyJoinMsg) ProtoMessage()    {}

func (m *NotifyJoinMsg) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *NotifyJoinMsg) GetRoomID() int64 {
	if m != nil && m.RoomID != nil {
		return *m.RoomID
	}
	return 0
}

type NotifyAction1Msg struct {
	UserID           *int64 `protobuf:"varint,1,req,name=userID" json:"userID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifyAction1Msg) Reset()         { *m = NotifyAction1Msg{} }
func (m *NotifyAction1Msg) String() string { return proto.CompactTextString(m) }
func (*NotifyAction1Msg) ProtoMessage()    {}

func (m *NotifyAction1Msg) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

type NotifyQuitMsg struct {
	UserID           *int64 `protobuf:"varint,1,req,name=userID" json:"userID,omitempty"`
	RoomID           *int64 `protobuf:"varint,2,req,name=roomID" json:"roomID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifyQuitMsg) Reset()         { *m = NotifyQuitMsg{} }
func (m *NotifyQuitMsg) String() string { return proto.CompactTextString(m) }
func (*NotifyQuitMsg) ProtoMessage()    {}

func (m *NotifyQuitMsg) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *NotifyQuitMsg) GetRoomID() int64 {
	if m != nil && m.RoomID != nil {
		return *m.RoomID
	}
	return 0
}

type ErrorMsg struct {
	ErrCode          *int32  `protobuf:"varint,1,req,name=errCode" json:"errCode,omitempty"`
	ErrMessage       *string `protobuf:"bytes,2,req,name=errMessage" json:"errMessage,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ErrorMsg) Reset()         { *m = ErrorMsg{} }
func (m *ErrorMsg) String() string { return proto.CompactTextString(m) }
func (*ErrorMsg) ProtoMessage()    {}

func (m *ErrorMsg) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *ErrorMsg) GetErrMessage() string {
	if m != nil && m.ErrMessage != nil {
		return *m.ErrMessage
	}
	return ""
}

func init() {
	proto.RegisterEnum("gs_protocol.Type", Type_name, Type_value)
	proto.RegisterEnum("gs_protocol.ErrorType", ErrorType_name, ErrorType_value)
}
