// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package gs_protocol is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Message
	ReqLogin
	ReqCreate
	ReqJoin
	ReqAction1
	ReqQuit
	ReqRoomList
	ResLogin
	ResCreate
	ResJoin
	ResAction1
	ResQuit
	ResRoomList
	NotifyJoinMsg
	NotifyAction1Msg
	NotifyQuitMsg
	ErrorMsg
*/
package gs_protocol

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Type int32

const (
	Type_Undefined      Type = 0
	Type_Login          Type = 1
	Type_Create         Type = 2
	Type_Join           Type = 3
	Type_DefinedAction1 Type = 4
	Type_Quit           Type = 5
	Type_RoomList       Type = 6
	Type_NotifyJoin     Type = 100
	Type_NotifyAction1  Type = 101
	Type_NotifyQuit     Type = 102
	Type_Error          Type = 1000
)

var Type_name = map[int32]string{
	0:    "Undefined",
	1:    "Login",
	2:    "Create",
	3:    "Join",
	4:    "DefinedAction1",
	5:    "Quit",
	6:    "RoomList",
	100:  "NotifyJoin",
	101:  "NotifyAction1",
	102:  "NotifyQuit",
	1000: "Error",
}
var Type_value = map[string]int32{
	"Undefined":      0,
	"Login":          1,
	"Create":         2,
	"Join":           3,
	"DefinedAction1": 4,
	"Quit":           5,
	"RoomList":       6,
	"NotifyJoin":     100,
	"NotifyAction1":  101,
	"NotifyQuit":     102,
	"Error":          1000,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

type ErrorType int32

const (
	ErrorType_Unknown ErrorType = 0
)

var ErrorType_name = map[int32]string{
	0: "Unknown",
}
var ErrorType_value = map[string]int32{
	"Unknown": 0,
}

func (x ErrorType) String() string {
	return proto.EnumName(ErrorType_name, int32(x))
}

type Message struct {
	Type Type `protobuf:"varint,1,opt,name=type,enum=gs_protocol.Type" json:"type,omitempty"`
	// request
	ReqLogin    *ReqLogin    `protobuf:"bytes,2,opt,name=req_login" json:"req_login,omitempty"`
	ReqCreate   *ReqCreate   `protobuf:"bytes,3,opt,name=req_create" json:"req_create,omitempty"`
	ReqJoin     *ReqJoin     `protobuf:"bytes,4,opt,name=req_join" json:"req_join,omitempty"`
	ReqAction1  *ReqAction1  `protobuf:"bytes,5,opt,name=req_action1" json:"req_action1,omitempty"`
	ReqQuit     *ReqQuit     `protobuf:"bytes,6,opt,name=req_quit" json:"req_quit,omitempty"`
	ReqRoomList *ReqRoomList `protobuf:"bytes,7,opt,name=req_room_list" json:"req_room_list,omitempty"`
	// response
	ResLogin    *ResLogin    `protobuf:"bytes,8,opt,name=res_login" json:"res_login,omitempty"`
	ResCreate   *ResCreate   `protobuf:"bytes,9,opt,name=res_create" json:"res_create,omitempty"`
	ResJoin     *ResJoin     `protobuf:"bytes,10,opt,name=res_join" json:"res_join,omitempty"`
	ResAction1  *ResAction1  `protobuf:"bytes,11,opt,name=res_action1" json:"res_action1,omitempty"`
	ResQuit     *ResQuit     `protobuf:"bytes,12,opt,name=res_quit" json:"res_quit,omitempty"`
	ResRoomList *ResRoomList `protobuf:"bytes,13,opt,name=res_room_list" json:"res_room_list,omitempty"`
	// notify
	NotifyJoin    *NotifyJoinMsg    `protobuf:"bytes,14,opt,name=notify_join" json:"notify_join,omitempty"`
	NotifyAction1 *NotifyAction1Msg `protobuf:"bytes,15,opt,name=notify_action1" json:"notify_action1,omitempty"`
	NotifyQuit    *NotifyQuitMsg    `protobuf:"bytes,16,opt,name=notify_quit" json:"notify_quit,omitempty"`
	// error
	Error *ErrorMsg `protobuf:"bytes,1000,opt,name=error" json:"error,omitempty"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}

func (m *Message) GetReqLogin() *ReqLogin {
	if m != nil {
		return m.ReqLogin
	}
	return nil
}

func (m *Message) GetReqCreate() *ReqCreate {
	if m != nil {
		return m.ReqCreate
	}
	return nil
}

func (m *Message) GetReqJoin() *ReqJoin {
	if m != nil {
		return m.ReqJoin
	}
	return nil
}

func (m *Message) GetReqAction1() *ReqAction1 {
	if m != nil {
		return m.ReqAction1
	}
	return nil
}

func (m *Message) GetReqQuit() *ReqQuit {
	if m != nil {
		return m.ReqQuit
	}
	return nil
}

func (m *Message) GetReqRoomList() *ReqRoomList {
	if m != nil {
		return m.ReqRoomList
	}
	return nil
}

func (m *Message) GetResLogin() *ResLogin {
	if m != nil {
		return m.ResLogin
	}
	return nil
}

func (m *Message) GetResCreate() *ResCreate {
	if m != nil {
		return m.ResCreate
	}
	return nil
}

func (m *Message) GetResJoin() *ResJoin {
	if m != nil {
		return m.ResJoin
	}
	return nil
}

func (m *Message) GetResAction1() *ResAction1 {
	if m != nil {
		return m.ResAction1
	}
	return nil
}

func (m *Message) GetResQuit() *ResQuit {
	if m != nil {
		return m.ResQuit
	}
	return nil
}

func (m *Message) GetResRoomList() *ResRoomList {
	if m != nil {
		return m.ResRoomList
	}
	return nil
}

func (m *Message) GetNotifyJoin() *NotifyJoinMsg {
	if m != nil {
		return m.NotifyJoin
	}
	return nil
}

func (m *Message) GetNotifyAction1() *NotifyAction1Msg {
	if m != nil {
		return m.NotifyAction1
	}
	return nil
}

func (m *Message) GetNotifyQuit() *NotifyQuitMsg {
	if m != nil {
		return m.NotifyQuit
	}
	return nil
}

func (m *Message) GetError() *ErrorMsg {
	if m != nil {
		return m.Error
	}
	return nil
}

// request payload
type ReqLogin struct {
	UserID int64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
}

func (m *ReqLogin) Reset()         { *m = ReqLogin{} }
func (m *ReqLogin) String() string { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()    {}

type ReqCreate struct {
	UserID int64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
}

func (m *ReqCreate) Reset()         { *m = ReqCreate{} }
func (m *ReqCreate) String() string { return proto.CompactTextString(m) }
func (*ReqCreate) ProtoMessage()    {}

type ReqJoin struct {
	UserID int64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	RoomID int64 `protobuf:"varint,2,opt,name=roomID" json:"roomID,omitempty"`
}

func (m *ReqJoin) Reset()         { *m = ReqJoin{} }
func (m *ReqJoin) String() string { return proto.CompactTextString(m) }
func (*ReqJoin) ProtoMessage()    {}

type ReqAction1 struct {
	UserID int64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
}

func (m *ReqAction1) Reset()         { *m = ReqAction1{} }
func (m *ReqAction1) String() string { return proto.CompactTextString(m) }
func (*ReqAction1) ProtoMessage()    {}

type ReqQuit struct {
	UserID int64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
}

func (m *ReqQuit) Reset()         { *m = ReqQuit{} }
func (m *ReqQuit) String() string { return proto.CompactTextString(m) }
func (*ReqQuit) ProtoMessage()    {}

type ReqRoomList struct {
	UserID int64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
}

func (m *ReqRoomList) Reset()         { *m = ReqRoomList{} }
func (m *ReqRoomList) String() string { return proto.CompactTextString(m) }
func (*ReqRoomList) ProtoMessage()    {}

// response payload
type ResLogin struct {
	UserID int64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	Result int32 `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
}

func (m *ResLogin) Reset()         { *m = ResLogin{} }
func (m *ResLogin) String() string { return proto.CompactTextString(m) }
func (*ResLogin) ProtoMessage()    {}

type ResCreate struct {
	UserID int64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	RoomID int64 `protobuf:"varint,2,opt,name=roomID" json:"roomID,omitempty"`
}

func (m *ResCreate) Reset()         { *m = ResCreate{} }
func (m *ResCreate) String() string { return proto.CompactTextString(m) }
func (*ResCreate) ProtoMessage()    {}

type ResJoin struct {
	UserID  int64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	RoomID  int64 `protobuf:"varint,2,opt,name=roomID" json:"roomID,omitempty"`
	Members int64 `protobuf:"varint,3,opt,name=members" json:"members,omitempty"`
}

func (m *ResJoin) Reset()         { *m = ResJoin{} }
func (m *ResJoin) String() string { return proto.CompactTextString(m) }
func (*ResJoin) ProtoMessage()    {}

type ResAction1 struct {
	UserID int64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	Result int32 `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
}

func (m *ResAction1) Reset()         { *m = ResAction1{} }
func (m *ResAction1) String() string { return proto.CompactTextString(m) }
func (*ResAction1) ProtoMessage()    {}

type ResQuit struct {
	UserID    int64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	IsSuccess int32 `protobuf:"varint,2,opt,name=isSuccess" json:"isSuccess,omitempty"`
}

func (m *ResQuit) Reset()         { *m = ResQuit{} }
func (m *ResQuit) String() string { return proto.CompactTextString(m) }
func (*ResQuit) ProtoMessage()    {}

type ResRoomList struct {
	UserID  int64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	RoomIDs int64 `protobuf:"varint,2,opt,name=roomIDs" json:"roomIDs,omitempty"`
}

func (m *ResRoomList) Reset()         { *m = ResRoomList{} }
func (m *ResRoomList) String() string { return proto.CompactTextString(m) }
func (*ResRoomList) ProtoMessage()    {}

// notify message type (for client)
type NotifyJoinMsg struct {
	UserID int64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	RoomID int64 `protobuf:"varint,2,opt,name=roomID" json:"roomID,omitempty"`
}

func (m *NotifyJoinMsg) Reset()         { *m = NotifyJoinMsg{} }
func (m *NotifyJoinMsg) String() string { return proto.CompactTextString(m) }
func (*NotifyJoinMsg) ProtoMessage()    {}

type NotifyAction1Msg struct {
	UserID int64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
}

func (m *NotifyAction1Msg) Reset()         { *m = NotifyAction1Msg{} }
func (m *NotifyAction1Msg) String() string { return proto.CompactTextString(m) }
func (*NotifyAction1Msg) ProtoMessage()    {}

type NotifyQuitMsg struct {
	UserID int64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	RoomID int64 `protobuf:"varint,2,opt,name=roomID" json:"roomID,omitempty"`
}

func (m *NotifyQuitMsg) Reset()         { *m = NotifyQuitMsg{} }
func (m *NotifyQuitMsg) String() string { return proto.CompactTextString(m) }
func (*NotifyQuitMsg) ProtoMessage()    {}

// error message
type ErrorMsg struct {
	ErrCode    int32  `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMessage string `protobuf:"bytes,2,opt,name=errMessage" json:"errMessage,omitempty"`
}

func (m *ErrorMsg) Reset()         { *m = ErrorMsg{} }
func (m *ErrorMsg) String() string { return proto.CompactTextString(m) }
func (*ErrorMsg) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("gs_protocol.Type", Type_name, Type_value)
	proto.RegisterEnum("gs_protocol.ErrorType", ErrorType_name, ErrorType_value)
}
